[package]
name = "jarvis-bigquery-sender"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nats = "0"
tokio = { version = "1", features = ["macros"] }
serde_json = "1"
jarvis-lib = { git = "https://github.com/JorritSalverda/jarvis-lib", tag = "0.1.21" }