[package]
name = "jarvis-bigquery-sender"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json_env_logger = { version = "0.1", features = ["iso-timestamps", "backtrace"] }
log = { version = "0.4", features = ["kv_unstable_std"]}
nats = "0.23"
tokio = { version = "1.5", features = ["macros"] }
serde_json = "1.0"
gcp-bigquery-client = "0.9"
jarvis-lib = { git = "https://github.com/JorritSalverda/jarvis-lib", tag = "0.1.53" }
kube = { version = "0.70", features = ["runtime", "derive"] }
signal-hook = "0.3"
