apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jarvis-bigquery-sender.fullname" . }}
  labels:
    {{- include "jarvis-bigquery-sender.labels" . | nindent 4 }}
data:
  bq-enable: {{ .Values.config.bqEnable | quote }}
  bq-init: {{ .Values.config.bqInit | quote }}
  bq-project-id: {{ .Values.config.bqProjectID | quote }}
  bq-dataset: {{ .Values.config.bqDataset | quote }}
  bq-table: {{ .Values.config.bqTable | quote }}
  nats-host: {{ .Values.config.natsHost | quote }}
  nats-subject: {{ .Values.config.natsSubject | quote }}
  nats-queue: {{ .Values.config.natsQueue | quote }}
  nats-queue-timeout: {{ .Values.config.natsQueueTimeout | quote }}
