apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jarvis-bigquery-sender.fullname" . }}
  labels:
    {{- include "jarvis-bigquery-sender.labels" . | nindent 4 }}
type: Opaque
data:
  keyfile.json: {{ .Values.secret.gcpServiceAccountKeyfile | toString | b64enc }}