name: Build

on: [push, pull_request]

jobs:
  calculate-version:
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7

  docker:
    runs-on: ubuntu-latest
    needs: calculate-version
    env:
      SEMVER: ${{ needs.calculate-version.outputs.semVer }}
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build docker image
      run: |
        IMAGE_NAME="jsalverda/jarvis-bigquery-sender"
        # https://docs.openfn.org/articles/2021/10/08/improving-multistage-docker-builds-using-buildx/
        docker buildx build \
          --tag $IMAGE_NAME:$SEMVER \
          --cache-from=type=registry,ref=$IMAGE_NAME-build-cache \
          --cache-to=type=registry,ref=$IMAGE_NAME-build-cache,mode=max \
          --file Dockerfile \
          --push \
          --progress=plain \
          .

  helm:
    runs-on: ubuntu-latest
    needs: calculate-version
    env:
      SEMVER: ${{ needs.calculate-version.outputs.semVer }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: azure/setup-helm@v1
    - run: helm lint --with-subcharts helm/jarvis-bigquery-sender
    - run: helm package --app-version $SEMVER --version $SEMVER --dependency-update helm/jarvis-bigquery-sender
