name: Build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
    - name: Clippy
      run: cargo clippy --no-deps -- --deny "warnings"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  bake:
    # needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build docker image
      run: |
        TAG=$(echo $GITHUB_SHA | head -c7)
        IMAGE="jsalverda/jarvis-bigquery-sender"

        docker buildx build --push --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from ${IMAGE}:dlc-builder --tag ${IMAGE}:dlc-builder --target builder --file Dockerfile .
        docker buildx build --push --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from ${IMAGE}:dlc-builder --cache-from ${IMAGE}:dlc --tag ${IMAGE}:dlc --tag ${IMAGE}:${TAG} --file Dockerfile .
