name: Build

on: [push, pull_request]

jobs:
  gitversion:
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - run: |
          git tag -f $GITVERSION_SEMVER
          git push origin $GITVERSION_SEMVER

  docker:
    runs-on: ubuntu-latest
    needs: gitversion
    env:
      GITVERSION_SEMVER: ${{ needs.gitversion.outputs.semVer }}
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build docker image
      run: |
        IMAGE_NAME="jsalverda/jarvis-bigquery-sender"
        # https://docs.openfn.org/articles/2021/10/08/improving-multistage-docker-builds-using-buildx/
        docker buildx build \
          --tag $IMAGE_NAME:$GITVERSION_SEMVER \
          --cache-from=type=registry,ref=$IMAGE_NAME-build-cache \
          --cache-to=type=registry,ref=$IMAGE_NAME-build-cache,mode=max \
          --file Dockerfile \
          --push \
          --progress=plain \
          .

  helm:
    runs-on: ubuntu-latest
    needs: gitversion
    env:
      GITVERSION_SEMVER: ${{ needs.gitversion.outputs.semVer }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: azure/setup-helm@v1
    - run: helm lint --with-subcharts helm/jarvis-bigquery-sender
    - run: helm package --app-version $GITVERSION_SEMVER --version $GITVERSION_SEMVER --dependency-update helm/jarvis-bigquery-sender
    - uses: actions/checkout@v2
      with:
        repository: JorritSalverda/helm-charts
        ref: master
        path: helm-charts
    - run: |
        mkdir -p helm-charts/charts
        cp jarvis-bigquery-sender-${GITVERSION_SEMVER}.tgz helm-charts/charts
        cd helm-charts
        helm repo index --url https://helm.jorritsalverda.com/ .
        git add --all
        git commit --allow-empty -m "jarvis-bigquery-sender $GITVERSION_SEMVER"
        git push origin master
